Repository OCA/stock-logistics-barcode, pull requests merged in 2018-12, with the labels that each got.

#167 [10.0][FIX] stock_scanner: Improve login method
  stock_scanner/__manifest__.py
  stock_scanner/models/scanner_hardware.py
  stock_scanner/tests/test_stock_scanner.py
Labels: approved, ready to merge

#169 [FIX] stock_scanner: Pass tests with auth_crypt
  stock_scanner/tests/test_stock_scanner.py
Labels: approved

#170 [8.0] Added ':' in http and change to markdown link
  mobile_app_inventory/README.rst
Labels: approved, enhancement
