Repository OCA/stock-logistics-barcode, pull requests merged in 2019-05, with the labels that each got.

#151 [11.0] [MIG] stock_scanner_location_info
  stock_scanner_location_info/README.rst
  stock_scanner_location_info/__init__.py
  stock_scanner_location_info/__manifest__.py
  stock_scanner_location_info/data/Location_informations/Location_informations.scenario
  stock_scanner_location_info/data/Location_informations/scanner_scenario_step_location_informations_informations_display.py
  stock_scanner_location_info/data/Location_informations/scanner_scenario_step_location_informations_location_selection.py
  stock_scanner_location_info/data/Location_informations/scanner_scenario_step_location_informations_unknown_location.py
  stock_scanner_location_info/images/scenario.png
  stock_scanner_location_info/readme/CONTRIBUTORS.rst
  stock_scanner_location_info/readme/DESCRIPTION.rst
  stock_scanner_location_info/readme/INSTALL.rst
Labels: approved, ready to merge

#150 [11.0] [MIG] stock_scanner_inventory
  stock_scanner_inventory/README.rst
  stock_scanner_inventory/__init__.py
  stock_scanner_inventory/__manifest__.py
  stock_scanner_inventory/data/Inventory/Inventory.scenario
  stock_scanner_inventory/data/Inventory/scanner_scenario_step_inventory_done.py
  stock_scanner_inventory/data/Inventory/scanner_scenario_step_inventory_end_confirm.py
  stock_scanner_inventory/data/Inventory/scanner_scenario_step_inventory_location_selection.py
  stock_scanner_inventory/data/Inventory/scanner_scenario_step_inventory_product_code.py
  stock_scanner_inventory/data/Inventory/scanner_scenario_step_inventory_product_quantity.py
  stock_scanner_inventory/data/Inventory/scanner_scenario_step_inventory_unknown_location.py
  stock_scanner_inventory/data/Inventory/scanner_scenario_step_inventory_unknown_product.py
  stock_scanner_inventory/images/scenario.png
  stock_scanner_inventory/readme/CONTRIBUTORS.rst
  stock_scanner_inventory/readme/DESCRIPTION.rst
  stock_scanner_inventory/readme/INSTALL.rst
Labels: approved

#180 [11.0][FIX] product_multi_aen: error on search multiple product references
  product_multi_ean/__manifest__.py
  product_multi_ean/models/product_product.py
  product_multi_ean/tests/test_product_multi_ean.py
Labels: approved, enhancement, ready to merge
