Repository OCA/stock-logistics-barcode, pull requests merged in 2020-07, with the labels that each got.

#254 [MIG][13.0] stock_barcodes_gs1: Migration to v13.0
  setup/stock_barcodes_gs1/odoo/addons/stock_barcodes_gs1
  setup/stock_barcodes_gs1/setup.py
  stock_barcodes_gs1/README.rst
  stock_barcodes_gs1/__init__.py
  stock_barcodes_gs1/__manifest__.py
  stock_barcodes_gs1/i18n/es.po
  stock_barcodes_gs1/i18n/stock_barcodes_gs1.pot
  stock_barcodes_gs1/readme/CONTRIBUTORS.rst
  stock_barcodes_gs1/readme/DESCRIPTION.rst
  stock_barcodes_gs1/readme/USAGE.rst
  stock_barcodes_gs1/static/description/icon.png
  stock_barcodes_gs1/static/description/index.html
  stock_barcodes_gs1/tests/__init__.py
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
  stock_barcodes_gs1/tests/test_stock_barcodes_new_lot_gs1.py
  stock_barcodes_gs1/wizard/__init__.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
  stock_barcodes_gs1/wizard/stock_production_lot.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#289 [11.0][FIX] stock_barcodes_gs1: Continue reading barcode if can not read it as gs1
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: approved, bot is merging ⏳

#290 [12.0][FIX] stock_barcodes_gs1: Continue reading barcode if can not read it as gs1
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: approved, bot is merging ⏳

#291 [13.0][FIX] stock_barcodes_gs1: Continue reading barcode if can not read it as gs1
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: approved, bot is merging ⏳

#121 [ADD][10.0] new module 'barcodes_search'
  barcodes_search/README.rst
  barcodes_search/__init__.py
  barcodes_search/__manifest__.py
  barcodes_search/demo/product_product.xml
  barcodes_search/demo/res_partner.xml
  barcodes_search/i18n/barcodes_search.pot
  barcodes_search/i18n/fr.po
  barcodes_search/i18n/fr_1.po
  barcodes_search/readme/CONTRIBUTORS.rst
  barcodes_search/readme/DESCRIPTION.rst
  barcodes_search/readme/DEVELOP.rst
  barcodes_search/readme/USAGE.rst
  barcodes_search/static/description/barcode_button_menu.png
  barcodes_search/static/description/partner_search.png
  barcodes_search/static/description/partner_user_search.png
  barcodes_search/static/description/price_product_search.png
  barcodes_search/static/src/js/barcodes_search.js
  barcodes_search/static/src/xml/barcodes_search.xml
  barcodes_search/tests/__init__.py
  barcodes_search/tests/test_barcode_search.py
  barcodes_search/views/templates.xml
  barcodes_search/wizards/__init__.py
  barcodes_search/wizards/barcode_search.py
  barcodes_search/wizards/barcode_search_line.py
  barcodes_search/wizards/barcode_search_view.xml
Labels: bot is merging ⏳, needs review
