Repository OCA/stock-logistics-barcode, pull requests merged in 2021-03, with the labels that each got.

#297 [12.0][IMP] stock_barcodes_gs1: Allow the use of double GS1-128 barcodes
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: approved, bot is merging ⏳

#318 [13.0][IMP] stock_barcodes: Add option to get lots automatically in inventory depends on removal strategy
  stock_barcodes/README.rst
  stock_barcodes/__manifest__.py
  stock_barcodes/i18n/es.po
  stock_barcodes/i18n/stock_barcodes.pot
  stock_barcodes/models/__init__.py
  stock_barcodes/models/res_config_settings.py
  stock_barcodes/readme/HISTORY.rst
  stock_barcodes/static/description/index.html
  stock_barcodes/tests/test_stock_barcodes.py
  stock_barcodes/tests/test_stock_barcodes_inventory.py
  stock_barcodes/views/res_config_settings_views.xml
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_inventory_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#323 [13.0][IMP] stock_barcodes_gs1: Allow the use of double GS1-128 barcodes
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: approved, bot is merging ⏳

#301 [13.0] [ADD] stock_picking_product_barcode_report_secondary_unit: Extend stock_picking_product_barcode_report for take care about secondary units
  oca_dependencies.txt
  setup/stock_picking_product_barcode_report_secondary_unit/odoo/addons/stock_picking_product_barcode_report_secondary_unit
  setup/stock_picking_product_barcode_report_secondary_unit/setup.py
  stock_picking_product_barcode_report_secondary_unit/README.rst
  stock_picking_product_barcode_report_secondary_unit/__init__.py
  stock_picking_product_barcode_report_secondary_unit/__manifest__.py
  stock_picking_product_barcode_report_secondary_unit/readme/CONFIGURE.rst
  stock_picking_product_barcode_report_secondary_unit/readme/CONTRIBUTORS.rst
  stock_picking_product_barcode_report_secondary_unit/readme/DESCRIPTION.rst
  stock_picking_product_barcode_report_secondary_unit/static/description/icon.png
  stock_picking_product_barcode_report_secondary_unit/static/description/index.html
  stock_picking_product_barcode_report_secondary_unit/tests/__init__.py
  stock_picking_product_barcode_report_secondary_unit/tests/test_stock_picking_product_barcode_report_secondary_unit.py
  stock_picking_product_barcode_report_secondary_unit/wizard/__init__.py
  stock_picking_product_barcode_report_secondary_unit/wizard/stock_barcode_selection_printing.py
Labels: bot is merging ⏳
