Repository OCA/stock-logistics-barcode, pull requests merged in 2021-09, with the labels that each got.

#362 [14.0][UPD] Copier update + barcodes_generator_abstract fixes
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/stale.yml
  .pre-commit-config.yaml
  barcodes_generator_abstract/README.rst
  barcodes_generator_abstract/readme/DEVELOP.rst
  barcodes_generator_abstract/static/description/index.html
Labels: bot is merging ⏳

#355 [FIX] stock_barcodes: avoid mixing tracked and untracked quants
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
Labels: approved, bot is merging ⏳

#346 [MIG] stock_barcodes: Cherry-picked
  base_gs1_barcode/models/gs1_barcode.py
  product_multi_barcode/models/product_product.py
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: approved, ready to merge, bot is merging ⏳

#331 [14.0] [mig] stock_barcodes_automatic_entry
  setup/stock_barcodes_automatic_entry/odoo/addons/stock_barcodes_automatic_entry
  setup/stock_barcodes_automatic_entry/setup.py
  stock_barcodes_automatic_entry/README.rst
  stock_barcodes_automatic_entry/__init__.py
  stock_barcodes_automatic_entry/__manifest__.py
  stock_barcodes_automatic_entry/i18n/stock_barcodes_automatic_entry.pot
  stock_barcodes_automatic_entry/readme/CONTRIBUTORS.rst
  stock_barcodes_automatic_entry/readme/DESCRIPTION.rst
  stock_barcodes_automatic_entry/readme/USAGE.rst
  stock_barcodes_automatic_entry/static/description/icon.png
  stock_barcodes_automatic_entry/static/description/index.html
  stock_barcodes_automatic_entry/static/src/css/button_style.css
  stock_barcodes_automatic_entry/static/src/js/stock_barcodes.js
  stock_barcodes_automatic_entry/views/assets.xml
Labels: approved, ready to merge, bot is merging ⏳
