Repository OCA/stock-logistics-barcode, pull requests merged in 2021-11, with the labels that each got.

#371 [13.0][FIX+IMP] stock_barcodes: Lost features from v12
  stock_barcodes/views/stock_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
Labels: bot is merging ⏳

#372 [14.0][FIX+IMP] stock_barcodes: Lost features from v12
  stock_barcodes/views/stock_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
Labels: approved, bot is merging ⏳

#364 [13.][IMP] stok_barcodes: add html field to track pending products
  stock_barcodes/__manifest__.py
  stock_barcodes/models/res_config_settings.py
  stock_barcodes/readme/HISTORY.rst
  stock_barcodes/security/security.xml
  stock_barcodes/templates/missing_moves_template.xml
  stock_barcodes/tests/test_stock_barcodes_new_lot.py
  stock_barcodes/tests/test_stock_barcodes_picking.py
  stock_barcodes/views/res_config_settings_views.xml
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#339 [MIG] barcodes_generator_location: Migration to 14.0
  barcodes_generator_location/README.rst
  barcodes_generator_location/__init__.py
  barcodes_generator_location/__manifest__.py
  barcodes_generator_location/demo/barcode_rule.xml
  barcodes_generator_location/demo/function.xml
  barcodes_generator_location/demo/ir_sequence.xml
  barcodes_generator_location/demo/stock_location.xml
  barcodes_generator_location/hooks.py
  barcodes_generator_location/i18n/barcodes_generator_location.pot
  barcodes_generator_location/i18n/es.po
  barcodes_generator_location/i18n/fr.po
  barcodes_generator_location/i18n/hr.po
  barcodes_generator_location/i18n/nl_NL.po
  barcodes_generator_location/models/__init__.py
  barcodes_generator_location/models/barcode_rule.py
  barcodes_generator_location/models/stock_location.py
  barcodes_generator_location/readme/CONFIGURE.rst
  barcodes_generator_location/readme/CONTRIBUTORS.rst
  barcodes_generator_location/readme/CREDITS.rst
  barcodes_generator_location/readme/DESCRIPTION.rst
  barcodes_generator_location/readme/USAGE.rst
  barcodes_generator_location/static/description/icon.png
  barcodes_generator_location/static/description/index.html
  barcodes_generator_location/static/description/stock_location_sequence_generation.png
  barcodes_generator_location/tests/__init__.py
  barcodes_generator_location/tests/test_barcode_generator.py
  barcodes_generator_location/views/stock_location.xml
  setup/barcodes_generator_location/odoo/addons/barcodes_generator_location
  setup/barcodes_generator_location/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#145 10.0 [MIG] stock_scanner_location_info
  stock_scanner_location_info/README.rst
  stock_scanner_location_info/__init__.py
  stock_scanner_location_info/__manifest__.py
  stock_scanner_location_info/data/Location_informations/Location_informations.scenario
  stock_scanner_location_info/data/Location_informations/scanner_scenario_step_location_informations_informations_display.py
  stock_scanner_location_info/data/Location_informations/scanner_scenario_step_location_informations_location_selection.py
  stock_scanner_location_info/data/Location_informations/scanner_scenario_step_location_informations_unknown_location.py
  stock_scanner_location_info/images/scenario.png
  stock_scanner_location_info/readme/CONTRIBUTORS.rst
  stock_scanner_location_info/readme/DESCRIPTION.rst
  stock_scanner_location_info/readme/INSTALL.rst
Labels: needs review, approved, ready to merge, bot is merging ⏳

#278 12.0 add product barcode constraint per company
  product_barcode_constraint_per_company/README.rst
  product_barcode_constraint_per_company/__init__.py
  product_barcode_constraint_per_company/__manifest__.py
  product_barcode_constraint_per_company/i18n/fr.po
  product_barcode_constraint_per_company/i18n/product_barcode_constraint_per_company.pot
  product_barcode_constraint_per_company/models/__init__.py
  product_barcode_constraint_per_company/models/product_product.py
  product_barcode_constraint_per_company/readme/CONTRIBUTORS.rst
  product_barcode_constraint_per_company/readme/DESCRIPTION.rst
  product_barcode_constraint_per_company/readme/ROADMAP.rst
  product_barcode_constraint_per_company/tests/__init__.py
  product_barcode_constraint_per_company/tests/test_module.py
Labels: approved, ready to merge, bot is merging ⏳
