Repository OCA/stock-logistics-barcode, pull requests merged in 2022-09, with the labels that each got.

#429 [14.0][FIX] stock_barcodes_gs1: Do action_confirm after gs1 is readed instead of action_done
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: enhancement, needs review, bot is merging ⏳

#430 [14.0][FIX] stock_barcodes: make actions readable by non-admin users.
  stock_barcodes/models/stock_barcodes_action.py
  stock_barcodes/models/stock_inventory.py
  stock_barcodes/models/stock_picking.py
  stock_barcodes/models/stock_picking_type.py
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_production_lot.py
Labels: approved, bot is merging ⏳

#431 [13.0][FIX] stock_barcodes: do not use PO UoM by default
  stock_barcodes/wizard/stock_barcodes_read_picking.py
Labels: bot is merging ⏳

#432 [14.0][FIX] stock_barcodes: remove last scan do not revert last action.
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_picking.py
Labels: bot is merging ⏳

#433 [13.0][FIX] stock_barcodes: remove last scan do not revert last action.
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_picking.py
Labels: bot is merging ⏳

#439 [14.0][IMP] stock_barcodes: Clean wizard values after the move to do has been reset
  stock_barcodes/wizard/stock_barcodes_read_todo.py
Labels: approved, bot is merging ⏳

#438 [IMP] stock_barcodes: Clean wizard values after the move to do has been reset
  stock_barcodes/wizard/stock_barcodes_read_todo.py
Labels: approved, bot is merging ⏳
