Repository OCA/stock-logistics-barcode, pull requests merged in 2022-10, with the labels that each got.

#386 [ADD] product_gs1_barcode and encoding (base_gs1_barcode)
  base_gs1_barcode/models/__init__.py
  base_gs1_barcode/models/gs1_encode_barcode.py
  product_gs1_barcode/README.rst
  product_gs1_barcode/__init__.py
  product_gs1_barcode/__manifest__.py
  product_gs1_barcode/models/__init__.py
  product_gs1_barcode/models/gs1_encode_barcode.py
  product_gs1_barcode/readme/CONTRIBUTORS.rst
  product_gs1_barcode/readme/DESCRIPTION.rst
  product_gs1_barcode/readme/USAGE.rst
  product_gs1_barcode/static/description/index.html
  product_gs1_barcode/tests/__init__.py
  product_gs1_barcode/tests/test_stock_barcodes_gs1.py
  setup/product_gs1_barcode/odoo/addons/product_gs1_barcode
  setup/product_gs1_barcode/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#411 [15.0][MIG] product_supplierinfo_barcode
  product_supplierinfo_barcode/README.rst
  product_supplierinfo_barcode/__init__.py
  product_supplierinfo_barcode/__manifest__.py
  product_supplierinfo_barcode/i18n/de.po
  product_supplierinfo_barcode/i18n/product_supplierinfo_barcode.pot
  product_supplierinfo_barcode/models/__init__.py
  product_supplierinfo_barcode/models/supplierinfo.py
  product_supplierinfo_barcode/readme/CONTRIBUTORS.rst
  product_supplierinfo_barcode/readme/DESCRIPTION.rst
  product_supplierinfo_barcode/static/description/icon.png
  product_supplierinfo_barcode/static/description/index.html
  product_supplierinfo_barcode/views/product_views.xml
  product_supplierinfo_barcode/views/supplierinfo_views.xml
  setup/product_supplierinfo_barcode/odoo/addons/product_supplierinfo_barcode
  setup/product_supplierinfo_barcode/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#387 [ADD] product_gs1_barcode and encoding (base_gs1_barcode)
  base_gs1_barcode/models/__init__.py
  base_gs1_barcode/models/gs1_encode_barcode.py
  product_gs1_barcode/README.rst
  product_gs1_barcode/__init__.py
  product_gs1_barcode/__manifest__.py
  product_gs1_barcode/models/__init__.py
  product_gs1_barcode/models/gs1_encode_barcode.py
  product_gs1_barcode/readme/CONTRIBUTORS.rst
  product_gs1_barcode/readme/DESCRIPTION.rst
  product_gs1_barcode/readme/USAGE.rst
  product_gs1_barcode/static/description/index.html
  product_gs1_barcode/tests/__init__.py
  product_gs1_barcode/tests/test_stock_barcodes_gs1.py
  setup/product_gs1_barcode/odoo/addons/product_gs1_barcode
  setup/product_gs1_barcode/setup.py
Labels: needs review, approved, bot is merging ⏳

#441 [IMP][14.0] barcodes_generator_abstract
  barcodes_generator_abstract/readme/CONFIGURE.rst
Labels: approved, bot is merging ⏳

#447 [14.0][IMP] stock_barcodes: function to calculate lot domain
  stock_barcodes/wizard/stock_barcodes_read.py
Labels: approved, bot is merging ⏳

#384 [14.0][FIX] product_supplierinfo_barcode: barcode field not available on purchase tree view on v14
  product_supplierinfo_barcode/readme/CONTRIBUTORS.rst
  product_supplierinfo_barcode/views/product_views.xml
Labels: approved, bot is merging ⏳

#449 [16.0][MIG] barcodes_generator_abstract (from 14.0 to 16.0)
  barcodes_generator_abstract/README.rst
  barcodes_generator_abstract/__init__.py
  barcodes_generator_abstract/__manifest__.py
  barcodes_generator_abstract/demo/res_users.xml
  barcodes_generator_abstract/i18n/am.po
  barcodes_generator_abstract/i18n/barcodes_generator_abstract.pot
  barcodes_generator_abstract/i18n/ca.po
  barcodes_generator_abstract/i18n/de.po
  barcodes_generator_abstract/i18n/el_GR.po
  barcodes_generator_abstract/i18n/es.po
  barcodes_generator_abstract/i18n/fi.po
  barcodes_generator_abstract/i18n/fr.po
  barcodes_generator_abstract/i18n/gl.po
  barcodes_generator_abstract/i18n/hr.po
  barcodes_generator_abstract/i18n/hr_HR.po
  barcodes_generator_abstract/i18n/it.po
  barcodes_generator_abstract/i18n/nl.po
  barcodes_generator_abstract/i18n/nl_NL.po
  barcodes_generator_abstract/i18n/pt.po
  barcodes_generator_abstract/i18n/pt_BR.po
  barcodes_generator_abstract/i18n/pt_PT.po
  barcodes_generator_abstract/i18n/sl.po
  barcodes_generator_abstract/i18n/tr.po
  barcodes_generator_abstract/i18n/zh_CN.po
  barcodes_generator_abstract/models/__init__.py
  barcodes_generator_abstract/models/barcode_generate_mixin.py
  barcodes_generator_abstract/models/barcode_rule.py
  barcodes_generator_abstract/readme/CONFIGURE.rst
  barcodes_generator_abstract/readme/CONTRIBUTORS.rst
  barcodes_generator_abstract/readme/CREDITS.rst
  barcodes_generator_abstract/readme/DESCRIPTION.rst
  barcodes_generator_abstract/readme/INSTALL.rst
  barcodes_generator_abstract/readme/ROADMAP.rst
  barcodes_generator_abstract/readme/USAGE.rst
  barcodes_generator_abstract/security/res_groups.xml
  barcodes_generator_abstract/static/description/barcode_nomenclature_form.png
  barcodes_generator_abstract/static/description/barcode_rule_form_manual.png
  barcodes_generator_abstract/static/description/barcode_rule_form_sequence.png
  barcodes_generator_abstract/static/description/icon.png
  barcodes_generator_abstract/static/description/index.html
  barcodes_generator_abstract/tests/__init__.py
  barcodes_generator_abstract/tests/models.py
  barcodes_generator_abstract/tests/test_barcodes_generator_abstract.py
  barcodes_generator_abstract/views/menu.xml
  barcodes_generator_abstract/views/view_barcode_rule.xml
  requirements.txt
  setup/barcodes_generator_abstract/odoo/addons/barcodes_generator_abstract
  setup/barcodes_generator_abstract/setup.py
  test-requirements.txt
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
