Repository OCA/stock-logistics-barcode, pull requests merged in 2022-03, with the labels that each got.

#363 [12.0][IMP] stock_barcodes: Allow get lots automatically depends on removal strategy for picking operations
  stock_barcodes/i18n/es.po
  stock_barcodes/i18n/stock_barcodes.pot
  stock_barcodes/models/res_config_settings.py
  stock_barcodes/tests/test_stock_barcodes_inventory.py
  stock_barcodes/tests/test_stock_barcodes_picking.py
  stock_barcodes/views/res_config_settings_views.xml
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
Labels: approved, bot is merging ⏳

#393 [13.0][IMP] stock_barcodes: Allow get lots automatically depends on removal strategy for picking operations
  stock_barcodes/models/res_config_settings.py
  stock_barcodes/tests/test_stock_barcodes_inventory.py
  stock_barcodes/tests/test_stock_barcodes_picking.py
  stock_barcodes/views/res_config_settings_views.xml
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
Labels: approved, bot is merging ⏳

#394 [14.0][FIX] product_multi_barcode: missing else on a condition
  product_multi_barcode/models/product_product.py
Labels: bot is merging ⏳

#388 [14.0] [MIG] stock_barcodes_gs1
  setup/stock_barcodes_gs1/odoo/addons/stock_barcodes_gs1
  setup/stock_barcodes_gs1/setup.py
  stock_barcodes_gs1/README.rst
  stock_barcodes_gs1/__init__.py
  stock_barcodes_gs1/__manifest__.py
  stock_barcodes_gs1/i18n/ca.po
  stock_barcodes_gs1/i18n/es.po
  stock_barcodes_gs1/i18n/stock_barcodes_gs1.pot
  stock_barcodes_gs1/readme/CONTRIBUTORS.rst
  stock_barcodes_gs1/readme/DESCRIPTION.rst
  stock_barcodes_gs1/readme/USAGE.rst
  stock_barcodes_gs1/static/description/icon.png
  stock_barcodes_gs1/static/description/index.html
  stock_barcodes_gs1/tests/__init__.py
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
  stock_barcodes_gs1/tests/test_stock_barcodes_new_lot_gs1.py
  stock_barcodes_gs1/wizard/__init__.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
  stock_barcodes_gs1/wizard/stock_production_lot.py
Labels: approved, ready to merge, bot is merging ⏳

#390 [MIG][14.0] stock_barcodes_gs1_expiry
  setup/stock_barcodes_gs1_expiry/odoo/addons/stock_barcodes_gs1_expiry
  setup/stock_barcodes_gs1_expiry/setup.py
  stock_barcodes_gs1_expiry/README.rst
  stock_barcodes_gs1_expiry/__init__.py
  stock_barcodes_gs1_expiry/__manifest__.py
  stock_barcodes_gs1_expiry/i18n/es.po
  stock_barcodes_gs1_expiry/i18n/stock_barcodes_gs1_expiry.pot
  stock_barcodes_gs1_expiry/readme/CONTRIBUTORS.rst
  stock_barcodes_gs1_expiry/readme/DESCRIPTION.rst
  stock_barcodes_gs1_expiry/readme/USAGE.rst
  stock_barcodes_gs1_expiry/static/description/icon.png
  stock_barcodes_gs1_expiry/static/description/index.html
  stock_barcodes_gs1_expiry/tests/__init__.py
  stock_barcodes_gs1_expiry/tests/test_stock_barcodes_gs1_expiry.py
  stock_barcodes_gs1_expiry/tests/test_stock_barcodes_new_lot_gs1_expiry.py
  stock_barcodes_gs1_expiry/wizard/__init__.py
  stock_barcodes_gs1_expiry/wizard/stock_barcodes_read.py
  stock_barcodes_gs1_expiry/wizard/stock_production_lot.py
  stock_barcodes_gs1_expiry/wizard/stock_production_lot_views.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#397 [14.0][FIX] stock_barcodes: company for lot creation
  stock_barcodes/tests/test_stock_barcodes.py
  stock_barcodes/tests/test_stock_barcodes_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_production_lot.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: bot is merging ⏳

#398 [13.0][FIX] stock_barcodes: company for lot creation
  stock_barcodes/tests/test_stock_barcodes.py
  stock_barcodes/tests/test_stock_barcodes_inventory.py
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_production_lot.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#399 [14.0][FIX] stock_barcodes: read act windows permission issue
  stock_barcodes/models/stock_inventory.py
  stock_barcodes/models/stock_picking.py
  stock_barcodes/models/stock_picking_type.py
Labels: approved, bot is merging ⏳

#396 ADD module sale_input_barcode
  sale_input_barcode/README.rst
  sale_input_barcode/__init__.py
  sale_input_barcode/__manifest__.py
  sale_input_barcode/models/__init__.py
  sale_input_barcode/models/product_barcode_line_mixin.py
  sale_input_barcode/models/sale_order.py
  sale_input_barcode/readme/CONFIGURE.rst
  sale_input_barcode/readme/CONTIBUTORS.rst
  sale_input_barcode/readme/DESCRIPTION.rst
  sale_input_barcode/tests/__init__.py
  sale_input_barcode/tests/test_module.py
  sale_input_barcode/views/sale.xml
  setup/sale_input_barcode/odoo/addons/sale_input_barcode
  setup/sale_input_barcode/setup.py
Labels: needs review, bot is merging ⏳

#403 Updated from template - Switch to Github actions
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
  barcodes_generator_location/tests/test_barcode_generator.py
Labels: enhancement, needs review
