Repository OCA/stock-logistics-barcode, pull requests merged in 2022-08, with the labels that each got.

#421 [13.0][FIX] stock_barcodes: Do not distribute lots for non tracking products for inventories
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_inventory_views.xml
  stock_barcodes/wizard/stock_barcodes_read_picking.py
Labels: approved, bot is merging ⏳

#422 [13.0][FIX] stock_barcodes: Apply auto lot after read packaging
  stock_barcodes/wizard/stock_barcodes_read_picking.py
Labels: approved, bot is merging ⏳

#423 [13.0][FIX] stock_barcodes: Get package quantities for fill moves todo moreresilient
  stock_barcodes/wizard/stock_barcodes_read_todo.py
Labels: approved, bot is merging ⏳

#424 [FIX] stock_barcodes: Do not distribute lots in inventory if a lot is selected in wizard
  stock_barcodes/tests/test_stock_barcodes_picking.py
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_views.xml
  stock_barcodes/wizard/stock_production_lot.py
  stock_barcodes_gs1_expiry/tests/test_stock_barcodes_gs1_expiry.py
  stock_barcodes_gs1_expiry/tests/test_stock_barcodes_new_lot_gs1_expiry.py
Labels: approved, bot is merging ⏳

#426 [FIX] stock_barcodes_gs1: Do action_confirm after gs1 is readed instead of action_done
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: approved, bot is merging ⏳

#418 [14.0][FIX] product_multi_barcode: Support product deletion.
  product_multi_barcode/models/product_barcode.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#417 [14.0][MIG/IMP] stock_barcodes: refactor, add guided mode
  stock_barcodes/README.rst
  stock_barcodes/__init__.py
  stock_barcodes/__manifest__.py
  stock_barcodes/data/stock_barcodes_action.xml
  stock_barcodes/data/stock_barcodes_option.xml
  stock_barcodes/hooks.py
  stock_barcodes/models/__init__.py
  stock_barcodes/models/res_config_settings.py
  stock_barcodes/models/stock_barcodes_action.py
  stock_barcodes/models/stock_barcodes_option.py
  stock_barcodes/models/stock_inventory.py
  stock_barcodes/models/stock_move_line.py
  stock_barcodes/models/stock_picking.py
  stock_barcodes/models/stock_picking_type.py
  stock_barcodes/readme/CONTRIBUTORS.rst
  stock_barcodes/readme/USAGE.rst
  stock_barcodes/security/ir.model.access.csv
  stock_barcodes/static/description/icon.png
  stock_barcodes/static/description/icon.svg
  stock_barcodes/static/description/index.html
  stock_barcodes/static/src/css/stock.scss
  stock_barcodes/static/src/js/barcodes_models_mixin.js
  stock_barcodes/static/src/js/basic_controller.js
  stock_barcodes/static/src/js/basic_fields.js
  stock_barcodes/static/src/js/form_view.js
  stock_barcodes/static/src/js/kanban_renderer.js
  stock_barcodes/static/src/js/numeric_step.js
  stock_barcodes/static/src/js/stock_barcodes.js
  stock_barcodes/static/src/sounds/bell.wav
  stock_barcodes/static/src/sounds/error.wav
  stock_barcodes/tests/test_stock_barcodes.py
  stock_barcodes/tests/test_stock_barcodes_inventory.py
  stock_barcodes/tests/test_stock_barcodes_new_lot.py
  stock_barcodes/tests/test_stock_barcodes_picking.py
  stock_barcodes/views/assets.xml
  stock_barcodes/views/res_config_settings_views.xml
  stock_barcodes/views/stock_barcodes_action_view.xml
  stock_barcodes/views/stock_barcodes_menu.xml
  stock_barcodes/views/stock_barcodes_option_view.xml
  stock_barcodes/views/stock_inventory_views.xml
  stock_barcodes/views/stock_picking_views.xml
  stock_barcodes/wizard/__init__.py
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_inventory_views.xml
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read_todo.py
  stock_barcodes/wizard/stock_barcodes_read_todo_view.xml
  stock_barcodes/wizard/stock_barcodes_read_views.xml
  stock_barcodes/wizard/stock_production_lot.py
  stock_barcodes/wizard/stock_production_lot_views.xml
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
  stock_barcodes_gs1/wizard/stock_production_lot.py
Labels: bot is merging ⏳
