Repository OCA/stock-logistics-barcode, pull requests merged in 2022-07, with the labels that each got.

#412 [14.0][UPD] product_multi_barcode: Added menu to see all barcodes. Up…
  product_multi_barcode/readme/CONTRIBUTORS.rst
  product_multi_barcode/views/product_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#414 [13.0][IMP] stock_barcodes_gs1: improvements after refactor of stock_barcodes
  stock_barcodes/tests/test_stock_barcodes.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
  stock_barcodes_gs1/wizard/stock_production_lot.py
Labels: approved, bot is merging ⏳

#415 [13.0][FIX] stock_barcodes: several small adjustments
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_todo_view.xml
  stock_barcodes/wizard/stock_barcodes_read_views.xml
Labels: approved, bot is merging ⏳

#413 [14.0][ADD] product_multi_barcode_menu
  product_multi_barcode_stock_menu/README.rst
  product_multi_barcode_stock_menu/__init__.py
  product_multi_barcode_stock_menu/__manifest__.py
  product_multi_barcode_stock_menu/readme/CONTRIBUTORS.rst
  product_multi_barcode_stock_menu/readme/DESCRIPTION.rst
  product_multi_barcode_stock_menu/readme/USAGE.rst
  product_multi_barcode_stock_menu/static/description/icon.png
  product_multi_barcode_stock_menu/views/barcode_view.xml
  setup/product_multi_barcode_stock_menu/odoo/addons/product_multi_barcode_stock_menu
  setup/product_multi_barcode_stock_menu/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#419 [13.0][IMP] stock_barcodes: Increase performance to compute product quantities into a package
  stock_barcodes/models/__init__.py
  stock_barcodes/models/stock_move_line.py
  stock_barcodes/models/stock_production_lot.py
  stock_barcodes/wizard/stock_barcodes_read_todo.py
Labels: enhancement, needs review, approved, bot is merging ⏳
