Repository OCA/stock-logistics-barcode, pull requests merged in 2022-11, with the labels that each got.

#453 [15.0][FIX] product_supplierinfo_barcode: add barcode field in tree view
  product_supplierinfo_barcode/readme/CONTRIBUTORS.rst
  product_supplierinfo_barcode/views/product_views.xml
Labels: bot is merging ⏳

#457 [14.0][FIX] pre-commit template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .t2d.yml
Labels: bot is merging ⏳

#452 [14.0][IMP] stock_barcodes: add Barcode Option Group for not planned pickings
  stock_barcodes/models/stock_picking.py
  stock_barcodes/models/stock_picking_type.py
  stock_barcodes/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#464 [15.0][FIX] pre-commit with copier
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#459 [15.0][MIG] stock_picking_product_barcode_report: Migration to 15.0
  requirements.txt
  setup/stock_picking_product_barcode_report/odoo/addons/stock_picking_product_barcode_report
  setup/stock_picking_product_barcode_report/setup.py
  stock_picking_product_barcode_report/README.rst
  stock_picking_product_barcode_report/__init__.py
  stock_picking_product_barcode_report/__manifest__.py
  stock_picking_product_barcode_report/controllers/__init__.py
  stock_picking_product_barcode_report/controllers/main.py
  stock_picking_product_barcode_report/data/paperformat_label.xml
  stock_picking_product_barcode_report/i18n/es.po
  stock_picking_product_barcode_report/i18n/stock_picking_product_barcode_report.pot
  stock_picking_product_barcode_report/migrations/15.0.1.0.0/pre-migration.py
  stock_picking_product_barcode_report/models/__init__.py
  stock_picking_product_barcode_report/models/ir_actions_report.py
  stock_picking_product_barcode_report/models/res_company.py
  stock_picking_product_barcode_report/models/res_config_settings.py
  stock_picking_product_barcode_report/readme/CONFIGURE.rst
  stock_picking_product_barcode_report/readme/CONTRIBUTORS.rst
  stock_picking_product_barcode_report/readme/DESCRIPTION.rst
  stock_picking_product_barcode_report/readme/USAGE.rst
  stock_picking_product_barcode_report/report/report_label_barcode.xml
  stock_picking_product_barcode_report/report/report_label_barcode_quant_package_template.xml
  stock_picking_product_barcode_report/report/report_label_barcode_template.xml
  stock_picking_product_barcode_report/security/ir.model.access.csv
  stock_picking_product_barcode_report/static/description/icon.png
  stock_picking_product_barcode_report/static/description/index.html
  stock_picking_product_barcode_report/tests/__init__.py
  stock_picking_product_barcode_report/tests/test_stock_picking_product_barcode_report.py
  stock_picking_product_barcode_report/views/ir_actions_report_view.xml
  stock_picking_product_barcode_report/views/res_config_settings_view.xml
  stock_picking_product_barcode_report/wizard/__init__.py
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing_view.xml
Labels: needs review, approved, migration, bot is merging ⏳
