Repository OCA/stock-logistics-barcode, pull requests merged in 2023-06, with the labels that each got.

#522 [IMP][16.0] barcodes_generator_product : various improvments
  barcodes_generator_abstract/__manifest__.py
  barcodes_generator_abstract/i18n/barcodes_generator_abstract.pot
  barcodes_generator_abstract/i18n/fr.po
  barcodes_generator_abstract/models/barcode_generate_mixin.py
  barcodes_generator_abstract/models/barcode_rule.py
  barcodes_generator_abstract/tests/test_barcodes_generator_abstract.py
  barcodes_generator_abstract/views/view_barcode_nomenclature.xml
  barcodes_generator_abstract/views/view_barcode_rule.xml
  barcodes_generator_product/i18n/barcodes_generator_product.pot
  barcodes_generator_product/i18n/fr.po
  barcodes_generator_product/models/product_template.py
  barcodes_generator_product/views/view_product_product.xml
  barcodes_generator_product/views/view_product_template.xml
  setup/barcodes_generator_abstract/setup.py
Labels: approved, bot is merging ⏳

#525 [FIX] barcodes_generator_abstract : align create algorithm with write … algorigthm
  barcodes_generator_abstract/models/barcode_generate_mixin.py
Labels: bot is merging ⏳

#425 14.0 mig product barcode constraint per company
  product_barcode_constraint_per_company/README.rst
  product_barcode_constraint_per_company/__init__.py
  product_barcode_constraint_per_company/__manifest__.py
  product_barcode_constraint_per_company/i18n/fr.po
  product_barcode_constraint_per_company/i18n/product_barcode_constraint_per_company.pot
  product_barcode_constraint_per_company/models/__init__.py
  product_barcode_constraint_per_company/models/product_product.py
  product_barcode_constraint_per_company/readme/CONTRIBUTORS.rst
  product_barcode_constraint_per_company/readme/DESCRIPTION.rst
  product_barcode_constraint_per_company/readme/ROADMAP.rst
  product_barcode_constraint_per_company/static/description/icon.png
  product_barcode_constraint_per_company/static/description/index.html
  product_barcode_constraint_per_company/tests/__init__.py
  product_barcode_constraint_per_company/tests/test_module.py
  setup/product_barcode_constraint_per_company/odoo/addons/product_barcode_constraint_per_company
  setup/product_barcode_constraint_per_company/setup.py
Labels: migration, bot is merging ⏳, stale
