Repository OCA/stock-logistics-barcode, pull requests merged in 2023-02, with the labels that each got.

#490 [IMP][15.0] stock_barcodes: Missing commits from v13
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read_todo.py
Labels: approved, bot is merging ⏳

#489 [FIX][14.0] stock_barcodes: missing commits from v13
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read_todo.py
Labels: approved, bot is merging ⏳

#488 [15.0][MIG]barcodes_generator_product
  barcodes_generator_product/README.rst
  barcodes_generator_product/__init__.py
  barcodes_generator_product/__manifest__.py
  barcodes_generator_product/demo/barcode_rule.xml
  barcodes_generator_product/demo/function.xml
  barcodes_generator_product/demo/product.xml
  barcodes_generator_product/demo/res_users.xml
  barcodes_generator_product/i18n/barcodes_generator_product.pot
  barcodes_generator_product/i18n/es_ES.po
  barcodes_generator_product/i18n/fr.po
  barcodes_generator_product/i18n/hr.po
  barcodes_generator_product/i18n/it.po
  barcodes_generator_product/i18n/nl_NL.po
  barcodes_generator_product/i18n/zh_CN.po
  barcodes_generator_product/models/__init__.py
  barcodes_generator_product/models/barcode_rule.py
  barcodes_generator_product/models/product_product.py
  barcodes_generator_product/models/product_template.py
  barcodes_generator_product/readme/CONFIGURE.rst
  barcodes_generator_product/readme/CONTRIBUTORS.rst
  barcodes_generator_product/readme/CREDITS.rst
  barcodes_generator_product/readme/DESCRIPTION.rst
  barcodes_generator_product/readme/USAGE.rst
  barcodes_generator_product/static/description/icon.png
  barcodes_generator_product/static/description/index.html
  barcodes_generator_product/static/description/product_template_manual_generation.png
  barcodes_generator_product/tests/__init__.py
  barcodes_generator_product/tests/test_barcodes_generator_product.py
  barcodes_generator_product/views/view_product_product.xml
  barcodes_generator_product/views/view_product_template.xml
  setup/barcodes_generator_product/odoo/addons/barcodes_generator_product
  setup/barcodes_generator_product/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#493 [15.0][FIX] stock_barcodes: put in pack call method fails
  stock_barcodes/models/stock_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking.py
Labels: approved, bot is merging ⏳

#484 [15.0][FIX] stock_barcodes: add migration script
  stock_barcodes/migrations/15.0.1.0.0/pre-migration.py
Labels: approved

#497 [15.0][MIG] stock_barcodes_gs1: Migration to version 15.0
  barcodes_generator_abstract/models/barcode_generate_mixin.py
  setup/stock_barcodes_gs1/odoo/addons/stock_barcodes_gs1
  setup/stock_barcodes_gs1/setup.py
  stock_barcodes_gs1/README.rst
  stock_barcodes_gs1/__init__.py
  stock_barcodes_gs1/__manifest__.py
  stock_barcodes_gs1/i18n/ca.po
  stock_barcodes_gs1/i18n/es.po
  stock_barcodes_gs1/i18n/stock_barcodes_gs1.pot
  stock_barcodes_gs1/readme/CONTRIBUTORS.rst
  stock_barcodes_gs1/readme/DESCRIPTION.rst
  stock_barcodes_gs1/readme/USAGE.rst
  stock_barcodes_gs1/static/description/icon.png
  stock_barcodes_gs1/static/description/index.html
  stock_barcodes_gs1/tests/__init__.py
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
  stock_barcodes_gs1/tests/test_stock_barcodes_new_lot_gs1.py
  stock_barcodes_gs1/wizard/__init__.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
  stock_barcodes_gs1/wizard/stock_production_lot.py
Labels: approved, bot is merging ⏳

#498 [13.0][FIX] stock_barcodes: Not pending moves when origin pending moves is stock move lines
  stock_barcodes/wizard/stock_barcodes_read_todo.py
Labels: approved, bot is merging ⏳

#500 [FIX] stock_barcodes: Not pending moves when origin pending moves is stock move lines
  stock_barcodes/wizard/stock_barcodes_read_todo.py
Labels: approved

#499 [FIX] stock_barcodes: Not pending moves when origin pending moves is stock move lines
  stock_barcodes/wizard/stock_barcodes_read_todo.py
Labels: approved, bot is merging ⏳

#456 [14.0][ADD] product_multi_barcode_supplierinfo
  product_multi_barcode_supplierinfo/__init__.py
  product_multi_barcode_supplierinfo/__manifest__.py
  product_multi_barcode_supplierinfo/hook.py
  product_multi_barcode_supplierinfo/models/__init__.py
  product_multi_barcode_supplierinfo/models/product_barcode.py
  product_multi_barcode_supplierinfo/models/supplierinfo.py
  product_multi_barcode_supplierinfo/readme/CONTRIBUTORS.rst
  product_multi_barcode_supplierinfo/readme/DESCRIPTION.rst
  product_multi_barcode_supplierinfo/tests/__init__.py
  product_multi_barcode_supplierinfo/tests/test_product_multi_barcode_supplierinfo.py
  product_multi_barcode_supplierinfo/views/product_template_view.xml
  setup/product_multi_barcode_supplierinfo/odoo/addons/product_multi_barcode_supplierinfo
  setup/product_multi_barcode_supplierinfo/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳
