Repository OCA/stock-logistics-barcode, pull requests merged in 2023-10, with the labels that each got.

#534 [15.0][IMP] copier update
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  barcodes_generator_product/demo/product.xml
Labels: bot is merging ⏳

#529 [16.0][MIG] product_multi_barcode_stock_menu: Migration to 16.0
  product_multi_barcode_stock_menu/README.rst
  product_multi_barcode_stock_menu/__init__.py
  product_multi_barcode_stock_menu/__manifest__.py
  product_multi_barcode_stock_menu/i18n/it.po
  product_multi_barcode_stock_menu/i18n/product_multi_barcode_stock_menu.pot
  product_multi_barcode_stock_menu/readme/CONTRIBUTORS.rst
  product_multi_barcode_stock_menu/readme/CREDITS.rst
  product_multi_barcode_stock_menu/readme/DESCRIPTION.rst
  product_multi_barcode_stock_menu/readme/USAGE.rst
  product_multi_barcode_stock_menu/static/description/icon.png
  product_multi_barcode_stock_menu/static/description/index.html
  product_multi_barcode_stock_menu/views/barcode_view.xml
  setup/product_multi_barcode_stock_menu/odoo/addons/product_multi_barcode_stock_menu
  setup/product_multi_barcode_stock_menu/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#530 [16.0][ADD] product_packaging_multi_barcode
  product_packaging_multi_barcode/README.rst
  product_packaging_multi_barcode/__init__.py
  product_packaging_multi_barcode/__manifest__.py
  product_packaging_multi_barcode/hooks.py
  product_packaging_multi_barcode/i18n/product_packaging_multi_barcode.pot
  product_packaging_multi_barcode/models/__init__.py
  product_packaging_multi_barcode/models/product_barcode.py
  product_packaging_multi_barcode/models/product_packaging.py
  product_packaging_multi_barcode/readme/CONTRIBUTORS.rst
  product_packaging_multi_barcode/readme/CREDITS.rst
  product_packaging_multi_barcode/readme/DESCRIPTION.rst
  product_packaging_multi_barcode/readme/USAGE.rst
  product_packaging_multi_barcode/static/description/icon.png
  product_packaging_multi_barcode/static/description/index.html
  product_packaging_multi_barcode/tests/__init__.py
  product_packaging_multi_barcode/tests/test_product_packaging_multi_barcode.py
  product_packaging_multi_barcode/views/product_packaging_view.xml
  setup/product_packaging_multi_barcode/odoo/addons/product_packaging_multi_barcode
  setup/product_packaging_multi_barcode/setup.py
Labels: needs review, approved, bot is merging ⏳

#495 [15.0][IMP] stock_barcodes: some improvements
  stock_barcodes/README.rst
  stock_barcodes/__manifest__.py
  stock_barcodes/data/stock_barcodes_action.xml
  stock_barcodes/data/stock_barcodes_option.xml
  stock_barcodes/models/__init__.py
  stock_barcodes/models/stock_barcodes_action.py
  stock_barcodes/models/stock_barcodes_option.py
  stock_barcodes/models/stock_move_line.py
  stock_barcodes/models/stock_picking.py
  stock_barcodes/models/stock_quant.py
  stock_barcodes/security/ir.model.access.csv
  stock_barcodes/static/description/index.html
  stock_barcodes/static/src/css/stock.scss
  stock_barcodes/tests/test_stock_barcodes.py
  stock_barcodes/tests/test_stock_barcodes_new_lot.py
  stock_barcodes/tests/test_stock_barcodes_picking.py
  stock_barcodes/views/stock_barcodes_option_view.xml
  stock_barcodes/wizard/__init__.py
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_inventory_views.xml
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read_todo.py
  stock_barcodes/wizard/stock_barcodes_read_views.xml
Labels: approved, bot is merging ⏳

#549 [16.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  barcodes_generator_abstract/tests/models.py
  barcodes_generator_product/demo/product.xml
Labels: help wanted, needs review

#533 [15.0][MIG] stock_barcodes_picking_batch: Migration to v15.0
  setup/stock_barcodes_picking_batch/odoo/addons/stock_barcodes_picking_batch
  setup/stock_barcodes_picking_batch/setup.py
  stock_barcodes_picking_batch/README.rst
  stock_barcodes_picking_batch/__init__.py
  stock_barcodes_picking_batch/__manifest__.py
  stock_barcodes_picking_batch/data/stock_barcodes_action.xml
  stock_barcodes_picking_batch/i18n/es.po
  stock_barcodes_picking_batch/i18n/stock_barcodes_picking_batch.pot
  stock_barcodes_picking_batch/models/__init__.py
  stock_barcodes_picking_batch/models/stock_picking_batch.py
  stock_barcodes_picking_batch/readme/CONTRIBUTORS.rst
  stock_barcodes_picking_batch/readme/DESCRIPTION.rst
  stock_barcodes_picking_batch/readme/USAGE.rst
  stock_barcodes_picking_batch/security/ir.model.access.csv
  stock_barcodes_picking_batch/static/description/icon.png
  stock_barcodes_picking_batch/static/description/index.html
  stock_barcodes_picking_batch/static/src/js/barcodes_models_mixin.js
  stock_barcodes_picking_batch/tests/__init__.py
  stock_barcodes_picking_batch/tests/test_stock_barcodes_picking_batch.py
  stock_barcodes_picking_batch/views/stock_picking_batch_views.xml
  stock_barcodes_picking_batch/wizard/__init__.py
  stock_barcodes_picking_batch/wizard/stock_barcodes_read_picking_batch.py
  stock_barcodes_picking_batch/wizard/stock_barcodes_read_picking_batch_views.xml
Labels: approved, bot is merging ⏳

#543 [15.0][IMP] stock_barcodes_gs1: Refactoring. Use Odoo core module to decode GS1 barcodes
  stock_barcodes_gs1/README.rst
  stock_barcodes_gs1/__manifest__.py
  stock_barcodes_gs1/static/description/index.html
  stock_barcodes_gs1/tests/__init__.py
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
  stock_barcodes_gs1/tests/test_stock_barcodes_new_lot_gs1.py
  stock_barcodes_gs1/wizard/__init__.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
  stock_barcodes_gs1/wizard/stock_production_lot.py
Labels: approved, ready to merge, bot is merging ⏳

#550 [14.0][IMP] update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  barcodes_generator_product/demo/product.xml
  base_gs1_barcode/views/gs1_barcode.xml
  product_multi_barcode/views/product_template_view.xml
  product_multi_barcode/views/product_view.xml
  product_multi_barcode_stock_menu/views/barcode_view.xml
  sale_input_barcode/i18n/fr_FR.po
  stock_barcodes/data/stock_barcodes_action.xml
  stock_barcodes/data/stock_barcodes_option.xml
  stock_barcodes/views/stock_barcodes_option_view.xml
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read_views.xml
Labels: approved, bot is merging ⏳
