Repository OCA/stock-logistics-barcode, pull requests merged in 2023-11, with the labels that each got.

#559 [15.0][IMP] stock_picking_product_barcode_report: Remove space under barcode
  stock_picking_product_barcode_report/controllers/main.py
Labels: approved, bot is merging ⏳

#560 [14.0][IMP] stock_barcodes: some improvements
  stock_barcodes/README.rst
  stock_barcodes/__manifest__.py
  stock_barcodes/data/stock_barcodes_action.xml
  stock_barcodes/data/stock_barcodes_option.xml
  stock_barcodes/models/__init__.py
  stock_barcodes/models/stock_barcodes_action.py
  stock_barcodes/models/stock_barcodes_option.py
  stock_barcodes/models/stock_move_line.py
  stock_barcodes/models/stock_picking.py
  stock_barcodes/models/stock_quant.py
  stock_barcodes/security/ir.model.access.csv
  stock_barcodes/static/description/index.html
  stock_barcodes/static/src/css/stock.scss
  stock_barcodes/tests/__init__.py
  stock_barcodes/tests/test_stock_barcodes.py
  stock_barcodes/tests/test_stock_barcodes_inventory.py
  stock_barcodes/tests/test_stock_barcodes_new_lot.py
  stock_barcodes/tests/test_stock_barcodes_picking.py
  stock_barcodes/views/stock_barcodes_option_view.xml
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_inventory_views.xml
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read_todo.py
  stock_barcodes/wizard/stock_barcodes_read_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#542 [16.0][IMP] product_packaging_multi_barcode: barcode product show packaging
  product_packaging_multi_barcode/__manifest__.py
  product_packaging_multi_barcode/views/product_template_view.xml
Labels: approved, ready to merge, bot is merging ⏳
