Repository OCA/stock-logistics-barcode, pull requests merged in 2023-05, with the labels that each got.

#504 [14.0][MIG] barcode_generator_package: migration to 14.0
  barcodes_generator_package/README.rst
  barcodes_generator_package/__init__.py
  barcodes_generator_package/__manifest__.py
  barcodes_generator_package/demo/barcode_rule.xml
  barcodes_generator_package/demo/function.xml
  barcodes_generator_package/demo/ir_sequence.xml
  barcodes_generator_package/demo/product_packaging.xml
  barcodes_generator_package/i18n/barcodes_generator_package.pot
  barcodes_generator_package/i18n/es.po
  barcodes_generator_package/i18n/es_ES.po
  barcodes_generator_package/i18n/fr.po
  barcodes_generator_package/i18n/hr.po
  barcodes_generator_package/i18n/nl_NL.po
  barcodes_generator_package/models/__init__.py
  barcodes_generator_package/models/barcode_rule.py
  barcodes_generator_package/models/product_packaging.py
  barcodes_generator_package/readme/CONFIGURE.rst
  barcodes_generator_package/readme/CONTRIBUTORS.rst
  barcodes_generator_package/readme/CREDITS.rst
  barcodes_generator_package/readme/DESCRIPTION.rst
  barcodes_generator_package/readme/USAGE.rst
  barcodes_generator_package/static/description/icon.png
  barcodes_generator_package/static/description/product_packaging_sequence_generation.png
  barcodes_generator_package/tests/__init__.py
  barcodes_generator_package/tests/test_barcode_generator.py
  barcodes_generator_package/views/product_packaging.xml
  setup/barcodes_generator_package/odoo/addons/barcodes_generator_package
  setup/barcodes_generator_package/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#450 [16.0][MIG] barcodes_generator_product (from 14 to 16)
  barcodes_generator_product/README.rst
  barcodes_generator_product/__init__.py
  barcodes_generator_product/__manifest__.py
  barcodes_generator_product/demo/barcode_rule.xml
  barcodes_generator_product/demo/product.xml
  barcodes_generator_product/demo/res_users.xml
  barcodes_generator_product/i18n/barcodes_generator_product.pot
  barcodes_generator_product/i18n/es_ES.po
  barcodes_generator_product/i18n/fr.po
  barcodes_generator_product/i18n/hr.po
  barcodes_generator_product/i18n/it.po
  barcodes_generator_product/i18n/nl_NL.po
  barcodes_generator_product/i18n/zh_CN.po
  barcodes_generator_product/models/__init__.py
  barcodes_generator_product/models/barcode_rule.py
  barcodes_generator_product/models/product_product.py
  barcodes_generator_product/models/product_template.py
  barcodes_generator_product/readme/CONFIGURE.rst
  barcodes_generator_product/readme/CONTRIBUTORS.rst
  barcodes_generator_product/readme/CREDITS.rst
  barcodes_generator_product/readme/DESCRIPTION.rst
  barcodes_generator_product/readme/USAGE.rst
  barcodes_generator_product/static/description/icon.png
  barcodes_generator_product/static/description/index.html
  barcodes_generator_product/static/description/product_template_manual_generation.png
  barcodes_generator_product/tests/__init__.py
  barcodes_generator_product/tests/test_barcodes_generator_product.py
  barcodes_generator_product/views/view_product_product.xml
  barcodes_generator_product/views/view_product_template.xml
  setup/barcodes_generator_product/odoo/addons/barcodes_generator_product
  setup/barcodes_generator_product/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#513 [ADD][12.0] Copier
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  barcodes_generator_abstract/__manifest__.py
  barcodes_generator_location/__manifest__.py
  barcodes_generator_partner/__manifest__.py
  barcodes_generator_product/__manifest__.py
  base_gs1_barcode/__manifest__.py
  product_barcode_constraint_per_company/__manifest__.py
  requirements.txt
  stock_barcodes_gs1/__manifest__.py
  stock_barcodes_gs1_expiry/__manifest__.py
  stock_barcodes_supplierinfo/__manifest__.py
  stock_inventory_barcode/__manifest__.py
  stock_scanner/data/scenarios/Login/stock_scanner.scanner_scenario_login_step_done.py
  stock_scanner/data/scenarios/Login/stock_scanner.scanner_scenario_login_step_error.py
  stock_scanner/data/scenarios/Login/stock_scanner.scanner_scenario_login_step_login.py
  stock_scanner/data/scenarios/Login/stock_scanner.scanner_scenario_login_step_pwd.py
  stock_scanner/data/scenarios/Logout/stock_scanner.scanner_scenario_logout_step_cancelled.py
  stock_scanner/data/scenarios/Logout/stock_scanner.scanner_scenario_logout_step_confirm.py
  stock_scanner/data/scenarios/Logout/stock_scanner.scanner_scenario_logout_step_confirmed.py
Labels: bot is merging ⏳

#506 [14.0][ADD] barcodes_generator_product_multi_barcode
  barcodes_generator_product_multi_barcode/README.rst
  barcodes_generator_product_multi_barcode/__init__.py
  barcodes_generator_product_multi_barcode/__manifest__.py
  barcodes_generator_product_multi_barcode/models/__init__.py
  barcodes_generator_product_multi_barcode/models/barcode_generate_mixin.py
  barcodes_generator_product_multi_barcode/readme/CONFIGURE.rst
  barcodes_generator_product_multi_barcode/readme/CONTRIBUTORS.rst
  barcodes_generator_product_multi_barcode/readme/DESCRIPTION.rst
  barcodes_generator_product_multi_barcode/readme/USAGE.rst
  barcodes_generator_product_multi_barcode/static/description/icon.png
  barcodes_generator_product_multi_barcode/tests/__init__.py
  barcodes_generator_product_multi_barcode/tests/test_multi_barcodes_generator_product.py
  setup/barcodes_generator_product_multi_barcode/odoo/addons/barcodes_generator_product_multi_barcode
  setup/barcodes_generator_product_multi_barcode/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#518 [FIX] barcodes_generator_product: #516
  barcodes_generator_abstract/models/barcode_generate_mixin.py
  barcodes_generator_abstract/readme/CONTRIBUTORS.rst
  barcodes_generator_product/demo/barcode_rule.xml
  barcodes_generator_product/readme/CONTRIBUTORS.rst
  barcodes_generator_product/tests/test_barcodes_generator_product.py
Labels: approved, bot is merging ⏳

#520 [15.0][IMP] stock_picking_product_barcode_report: Posibility to print labels from HTML field
  stock_picking_product_barcode_report/__manifest__.py
  stock_picking_product_barcode_report/data/paperformat_label.xml
  stock_picking_product_barcode_report/i18n/es.po
  stock_picking_product_barcode_report/i18n/stock_picking_product_barcode_report.pot
  stock_picking_product_barcode_report/models/ir_actions_report.py
  stock_picking_product_barcode_report/report/report_label_barcode.xml
  stock_picking_product_barcode_report/report/report_label_custom.xml
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing_view.xml
Labels: approved, bot is merging ⏳
