Repository OCA/stock-logistics-barcode, pull requests merged in 2024-05, with the labels that each got.

#604 [15.0][FIX] stock_barcodes: Do not search quant when a only lot is scanned
  stock_barcodes/wizard/stock_barcodes_read.py
Labels: approved, bot is merging ⏳

#605 [15.0][FIX] stock_barcodes: Error when using arrows on Inventory Overview
  stock_barcodes/static/src/js/kanban_renderer.js
Labels: enhancement, needs review, approved, bot is merging ⏳

#600 [15.0][IMP] stock_barcodes: Skip backorder creation for pickings with all moves read or ignore pending quantities
  stock_barcodes/models/stock_picking.py
Labels: approved, bot is merging ⏳

#612 12.0 barcodes_generator_product fix show fields in product template
  barcodes_generator_product/__manifest__.py
  barcodes_generator_product/views/view_product_template.xml
Labels: bot is merging ⏳

#613 [15.0][FIX] stock_barcodes: todo lines not refresh data for automatic mode when a new stock move line is created
  stock_barcodes/wizard/stock_barcodes_read_picking.py
Labels: approved, bot is merging ⏳

#616 [IMP] barcodes_generator_abstract: set 'python-barcode' as external_dependencies
  barcodes_generator_abstract/__manifest__.py
  setup/barcodes_generator_abstract/setup.py
Labels: approved, bot is merging ⏳

#618 [15.0][FIX] stock_barcodes: The field state from stock move line compared is not correct
  stock_barcodes/models/stock_picking.py
Labels: approved, bot is merging ⏳

#615 [17.0][MIG] barcodes_generator_abstract: Migration to 17.0
  barcodes_generator_abstract/README.rst
  barcodes_generator_abstract/__init__.py
  barcodes_generator_abstract/__manifest__.py
  barcodes_generator_abstract/demo/res_users.xml
  barcodes_generator_abstract/i18n/am.po
  barcodes_generator_abstract/i18n/barcodes_generator_abstract.pot
  barcodes_generator_abstract/i18n/ca.po
  barcodes_generator_abstract/i18n/de.po
  barcodes_generator_abstract/i18n/el_GR.po
  barcodes_generator_abstract/i18n/es.po
  barcodes_generator_abstract/i18n/fi.po
  barcodes_generator_abstract/i18n/fr.po
  barcodes_generator_abstract/i18n/gl.po
  barcodes_generator_abstract/i18n/hr.po
  barcodes_generator_abstract/i18n/hr_HR.po
  barcodes_generator_abstract/i18n/it.po
  barcodes_generator_abstract/i18n/nl.po
  barcodes_generator_abstract/i18n/nl_NL.po
  barcodes_generator_abstract/i18n/pt.po
  barcodes_generator_abstract/i18n/pt_BR.po
  barcodes_generator_abstract/i18n/pt_PT.po
  barcodes_generator_abstract/i18n/sl.po
  barcodes_generator_abstract/i18n/tr.po
  barcodes_generator_abstract/i18n/zh_CN.po
  barcodes_generator_abstract/models/__init__.py
  barcodes_generator_abstract/models/barcode_generate_mixin.py
  barcodes_generator_abstract/models/barcode_rule.py
  barcodes_generator_abstract/pyproject.toml
  barcodes_generator_abstract/readme/CONFIGURE.md
  barcodes_generator_abstract/readme/CONTRIBUTORS.md
  barcodes_generator_abstract/readme/CREDITS.md
  barcodes_generator_abstract/readme/DESCRIPTION.md
  barcodes_generator_abstract/readme/INSTALL.md
  barcodes_generator_abstract/readme/ROADMAP.md
  barcodes_generator_abstract/readme/USAGE.md
  barcodes_generator_abstract/security/res_groups.xml
  barcodes_generator_abstract/static/description/barcode_nomenclature_form.png
  barcodes_generator_abstract/static/description/barcode_rule_form_manual.png
  barcodes_generator_abstract/static/description/barcode_rule_form_sequence.png
  barcodes_generator_abstract/static/description/icon.png
  barcodes_generator_abstract/static/description/index.html
  barcodes_generator_abstract/tests/__init__.py
  barcodes_generator_abstract/tests/models.py
  barcodes_generator_abstract/tests/test_barcodes_generator_abstract.py
  barcodes_generator_abstract/views/menu.xml
  barcodes_generator_abstract/views/view_barcode_nomenclature.xml
  barcodes_generator_abstract/views/view_barcode_rule.xml
  requirements.txt
  test-requirements.txt
Labels: approved, bot is merging ⏳
