Repository OCA/stock-logistics-barcode, pull requests merged in 2024-03, with the labels that each got.

#588 [15.0][IMP] stock_picking_product_barcode_report: Allow force qty using context
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
Labels: approved, bot is merging ⏳

#567 [15.0][IMP] stock_picking_product_barcode_report: Add possibility to print labels from stock.move.line
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing_view.xml
Labels: enhancement, approved, bot is merging ⏳

#576 [16.0][MIG] barcodes_generator_location
  barcodes_generator_location/README.rst
  barcodes_generator_location/__init__.py
  barcodes_generator_location/__manifest__.py
  barcodes_generator_location/demo/barcode_rule.xml
  barcodes_generator_location/demo/function.xml
  barcodes_generator_location/demo/ir_sequence.xml
  barcodes_generator_location/demo/stock_location.xml
  barcodes_generator_location/hooks.py
  barcodes_generator_location/i18n/barcodes_generator_location.pot
  barcodes_generator_location/i18n/es.po
  barcodes_generator_location/i18n/fr.po
  barcodes_generator_location/i18n/hr.po
  barcodes_generator_location/i18n/nl_NL.po
  barcodes_generator_location/models/__init__.py
  barcodes_generator_location/models/barcode_rule.py
  barcodes_generator_location/models/stock_location.py
  barcodes_generator_location/readme/CONFIGURE.rst
  barcodes_generator_location/readme/CONTRIBUTORS.rst
  barcodes_generator_location/readme/CREDITS.rst
  barcodes_generator_location/readme/DESCRIPTION.rst
  barcodes_generator_location/readme/USAGE.rst
  barcodes_generator_location/static/description/icon.png
  barcodes_generator_location/static/description/index.html
  barcodes_generator_location/static/description/stock_location_sequence_generation.png
  barcodes_generator_location/tests/__init__.py
  barcodes_generator_location/tests/test_barcode_generator.py
  barcodes_generator_location/views/stock_location.xml
  setup/barcodes_generator_location/odoo/addons/barcodes_generator_location
  setup/barcodes_generator_location/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#595 [15.0][IMP] stock_picking_product_barcode_report: Add product packaging to wizard.
  stock_picking_product_barcode_report/README.rst
  stock_picking_product_barcode_report/__manifest__.py
  stock_picking_product_barcode_report/report/report_base_label.xml
  stock_picking_product_barcode_report/report/report_label_barcode.xml
  stock_picking_product_barcode_report/static/description/index.html
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing_view.xml
Labels: approved, bot is merging ⏳

#553 [15.0][ADD] stock_barcodes_picking_batch_revision: New module
  setup/stock_barcodes_picking_batch_revision/odoo/addons/stock_barcodes_picking_batch_revision
  setup/stock_barcodes_picking_batch_revision/setup.py
  stock_barcodes_picking_batch_revision/README.rst
  stock_barcodes_picking_batch_revision/__init__.py
  stock_barcodes_picking_batch_revision/__manifest__.py
  stock_barcodes_picking_batch_revision/data/stock_barcodes_action.xml
  stock_barcodes_picking_batch_revision/i18n/es.po
  stock_barcodes_picking_batch_revision/i18n/stock_barcodes_picking_batch.pot
  stock_barcodes_picking_batch_revision/models/__init__.py
  stock_barcodes_picking_batch_revision/models/stock_move_line.py
  stock_barcodes_picking_batch_revision/models/stock_picking_batch.py
  stock_barcodes_picking_batch_revision/readme/CONTRIBUTORS.rst
  stock_barcodes_picking_batch_revision/readme/DESCRIPTION.rst
  stock_barcodes_picking_batch_revision/readme/USAGE.rst
  stock_barcodes_picking_batch_revision/static/description/icon.png
  stock_barcodes_picking_batch_revision/static/description/index.html
  stock_barcodes_picking_batch_revision/static/src/js/boolean_toggle_big.js
  stock_barcodes_picking_batch_revision/static/src/scss/boolean_toggle_big.scss
  stock_barcodes_picking_batch_revision/views/stock_picking_batch_views.xml
  stock_barcodes_picking_batch_revision/wizard/__init__.py
  stock_barcodes_picking_batch_revision/wizard/stock_barcodes_read_picking_batch.py
  stock_barcodes_picking_batch_revision/wizard/stock_barcodes_read_picking_batch_views.xml
  stock_barcodes_picking_batch_revision/wizard/stock_barcodes_read_todo.py
Labels: approved, ready to merge, bot is merging ⏳
