Repository OCA/stock-logistics-barcode, pull requests merged in 2024-01, with the labels that each got.

#571 [IMP] barcodes_generator_product: clarify documentation
  barcodes_generator_product/README.rst
  barcodes_generator_product/readme/DESCRIPTION.rst
  barcodes_generator_product/static/description/index.html
Labels: bot is merging ⏳

#573 [15.0] [IMP] barcodes_generator_product: clarify documentation
  barcodes_generator_product/README.rst
  barcodes_generator_product/readme/DESCRIPTION.rst
  barcodes_generator_product/static/description/index.html
Labels: bot is merging ⏳

#574 [16.0] [IMP] barcodes_generator_product: clarify documentation
  barcodes_generator_product/README.rst
  barcodes_generator_product/readme/DESCRIPTION.rst
  barcodes_generator_product/static/description/index.html
Labels: bot is merging ⏳

#575 [14.0] [ADD] barcode_generator_product_variant
  barcode_generator_product_variant/README.rst
  barcode_generator_product_variant/__init__.py
  barcode_generator_product_variant/__manifest__.py
  barcode_generator_product_variant/demo/barcode_rule_demo.xml
  barcode_generator_product_variant/models/__init__.py
  barcode_generator_product_variant/models/product_template.py
  barcode_generator_product_variant/readme/CONTRIBUTORS.rst
  barcode_generator_product_variant/readme/DESCRIPTION.rst
  barcode_generator_product_variant/readme/USAGE.rst
  barcode_generator_product_variant/security/ir.model.access.csv
  barcode_generator_product_variant/static/description/index.html
  barcode_generator_product_variant/tests/__init__.py
  barcode_generator_product_variant/tests/test_barcode_generator_product_variant.py
  barcode_generator_product_variant/views/product_template_views.xml
  barcode_generator_product_variant/wizards/__init__.py
  barcode_generator_product_variant/wizards/product_product_barcode_wizard.py
  barcode_generator_product_variant/wizards/product_product_barcode_wizard_views.xml
  barcodes_generator_abstract/models/barcode_generate_mixin.py
  barcodes_generator_abstract/models/barcode_rule.py
  barcodes_generator_abstract/views/view_barcode_rule.xml
  setup/barcode_generator_product_variant/odoo/addons/barcode_generator_product_variant
  setup/barcode_generator_product_variant/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#572 [14.0][FIX] barcodes_generator_product_multi_barcode: rename model file
  barcodes_generator_product_multi_barcode/models/__init__.py
  barcodes_generator_product_multi_barcode/models/product_product.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#577 [UPD] Copier update
  .copier-answers.yml
  .gitignore
  .oca_hooks.cfg
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#544 product_multi_barcode: add missing index
  product_multi_barcode/models/product_barcode.py
Labels: approved, ready to merge, bot is merging ⏳

#552 [12.0][FIX] barcodes_generator_[abstract,product]: Respect create vals
  barcodes_generator_abstract/models/barcode_generate_mixin.py
  barcodes_generator_product/models/product_template.py
  barcodes_generator_product/tests/test_barcodes_generator_product.py
Labels: enhancement, needs review, approved, bot is merging ⏳
