Repository OCA/stock-logistics-barcode, pull requests merged in 2024-07, with the labels that each got.

#563 [16.0][IMP]product_packaging_multi_barcode: Display barcode packaging
  product_packaging_multi_barcode/README.rst
  product_packaging_multi_barcode/__manifest__.py
  product_packaging_multi_barcode/models/product_barcode.py
  product_packaging_multi_barcode/static/description/index.html
  product_packaging_multi_barcode/views/barcode_view.xml
Labels: enhancement, approved, bot is merging ⏳

#590 [16.0][IMP] product_packaging_multi_barcode: remove packaging_id of product.barcode on product form view
  product_packaging_multi_barcode/__manifest__.py
  product_packaging_multi_barcode/views/product_template_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#630 [15.0][IMP] stock_barcodes_gs1_secondary_unit: Set todo secondary qty from move…
  stock_barcodes_gs1_secondary_unit/wizard/stock_barcodes_read_todo.py
Labels: approved, bot is merging ⏳

#626 [15.0][IMP] stock_picking_product_barcode_report: Add helper method to create labels from other models
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
Labels: approved, bot is merging ⏳
