Repository OCA/stock-logistics-barcode, pull requests merged in 2024-04, with the labels that each got.

#551 [15.0][IMP] stock_barcodes: Filled all fields if they is defined in options as filled default.
  stock_barcodes/models/stock_barcodes_option.py
  stock_barcodes/models/stock_move_line.py
  stock_barcodes/models/stock_picking_type.py
  stock_barcodes/models/stock_quant.py
  stock_barcodes/static/src/css/stock.scss
  stock_barcodes/static/src/js/basic_controller.js
  stock_barcodes/views/stock_barcodes_menu.xml
  stock_barcodes/views/stock_barcodes_option_view.xml
  stock_barcodes/views/stock_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read.py
  stock_barcodes/wizard/stock_barcodes_read_inventory.py
  stock_barcodes/wizard/stock_barcodes_read_inventory_views.xml
  stock_barcodes/wizard/stock_barcodes_read_picking.py
  stock_barcodes/wizard/stock_barcodes_read_picking_views.xml
  stock_barcodes/wizard/stock_barcodes_read_todo.py
  stock_barcodes/wizard/stock_barcodes_read_todo_view.xml
  stock_barcodes/wizard/stock_barcodes_read_views.xml
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
Labels: approved, bot is merging ⏳

#597 [15.0][I18N] stock_barcodes_picking_batch_revision: Fix translations generated by oca-ci
  stock_barcodes_picking_batch_revision/i18n/es.po
  stock_barcodes_picking_batch_revision/i18n/stock_barcodes_picking_batch.pot
Labels: bot is merging ⏳

#508 [15.0][ADD] stock_barcodes_elaboration: New module for display elaborations in barcode interface
  setup/stock_barcodes_elaboration/odoo/addons/stock_barcodes_elaboration
  setup/stock_barcodes_elaboration/setup.py
  stock_barcodes_elaboration/README.rst
  stock_barcodes_elaboration/__init__.py
  stock_barcodes_elaboration/__manifest__.py
  stock_barcodes_elaboration/readme/CONTRIBUTORS.rst
  stock_barcodes_elaboration/readme/DESCRIPTION.rst
  stock_barcodes_elaboration/readme/USAGE.rst
  stock_barcodes_elaboration/static/description/icon.png
  stock_barcodes_elaboration/static/description/index.html
  stock_barcodes_elaboration/static/src/css/stock_barcodes_elaboration.scss
  stock_barcodes_elaboration/wizard/__init__.py
  stock_barcodes_elaboration/wizard/stock_barcodes_read_picking_views.xml
  stock_barcodes_elaboration/wizard/stock_barcodes_read_todo.py
  stock_barcodes_elaboration/wizard/stock_barcodes_read_todo_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#598 [15.0][IMP] stock_picking_product_barcode_report: Allow to select language on wizard to print labels.
  stock_picking_product_barcode_report/report/report_base_label.xml
  stock_picking_product_barcode_report/report/report_label_barcode_template.xml
  stock_picking_product_barcode_report/report/report_label_custom.xml
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing.py
  stock_picking_product_barcode_report/wizard/stock_barcode_selection_printing_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#557 [15.0][IMP] stock_barcodes_gs1: Add hook process gs1 parsed values by other modules
  stock_barcodes_gs1/tests/test_stock_barcodes_gs1.py
  stock_barcodes_gs1/wizard/stock_barcodes_read.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#496 [15.0][MIG] stock_barcodes_gs1_secondary_unit: Migration to version 15.0
  setup/stock_barcodes_gs1_secondary_unit/odoo/addons/stock_barcodes_gs1_secondary_unit
  setup/stock_barcodes_gs1_secondary_unit/setup.py
  stock_barcodes_gs1_secondary_unit/README.rst
  stock_barcodes_gs1_secondary_unit/__init__.py
  stock_barcodes_gs1_secondary_unit/__manifest__.py
  stock_barcodes_gs1_secondary_unit/i18n/es.po
  stock_barcodes_gs1_secondary_unit/i18n/stock_barcodes_gs1_secondary_unit.pot
  stock_barcodes_gs1_secondary_unit/models/__init__.py
  stock_barcodes_gs1_secondary_unit/models/product_second_unit.py
  stock_barcodes_gs1_secondary_unit/models/stock_barcodes_read_log.py
  stock_barcodes_gs1_secondary_unit/models/stock_move_line.py
  stock_barcodes_gs1_secondary_unit/readme/CONTRIBUTORS.rst
  stock_barcodes_gs1_secondary_unit/readme/DESCRIPTION.rst
  stock_barcodes_gs1_secondary_unit/readme/USAGE.rst
  stock_barcodes_gs1_secondary_unit/static/description/icon.png
  stock_barcodes_gs1_secondary_unit/static/description/index.html
  stock_barcodes_gs1_secondary_unit/tests/__init__.py
  stock_barcodes_gs1_secondary_unit/tests/test_stock_barcodes_gs1_secondary_unit.py
  stock_barcodes_gs1_secondary_unit/views/product_views.xml
  stock_barcodes_gs1_secondary_unit/wizard/__init__.py
  stock_barcodes_gs1_secondary_unit/wizard/stock_barcodes_read.py
  stock_barcodes_gs1_secondary_unit/wizard/stock_barcodes_read_picking.py
  stock_barcodes_gs1_secondary_unit/wizard/stock_barcodes_read_picking_views.xml
  stock_barcodes_gs1_secondary_unit/wizard/stock_barcodes_read_todo.py
  stock_barcodes_gs1_secondary_unit/wizard/stock_barcodes_read_todo_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#540 [15.0][MIG] stock_barcodes_gs1_expiry: Migration to v15
  setup/stock_barcodes_gs1_expiry/odoo/addons/stock_barcodes_gs1_expiry
  setup/stock_barcodes_gs1_expiry/setup.py
  stock_barcodes_gs1_expiry/README.rst
  stock_barcodes_gs1_expiry/__init__.py
  stock_barcodes_gs1_expiry/__manifest__.py
  stock_barcodes_gs1_expiry/i18n/es.po
  stock_barcodes_gs1_expiry/i18n/stock_barcodes_gs1_expiry.pot
  stock_barcodes_gs1_expiry/readme/CONTRIBUTORS.rst
  stock_barcodes_gs1_expiry/readme/DESCRIPTION.rst
  stock_barcodes_gs1_expiry/readme/USAGE.rst
  stock_barcodes_gs1_expiry/static/description/icon.png
  stock_barcodes_gs1_expiry/static/description/index.html
  stock_barcodes_gs1_expiry/tests/__init__.py
  stock_barcodes_gs1_expiry/tests/test_stock_barcodes_gs1_expiry.py
  stock_barcodes_gs1_expiry/wizard/__init__.py
  stock_barcodes_gs1_expiry/wizard/stock_barcodes_read.py
  stock_barcodes_gs1_expiry/wizard/stock_barcodes_read_views.xml
  test-requirements.txt
Labels: needs review, migration, bot is merging ⏳

#601 [15.0][IMP] stock_barcodes: Add option group to allow to select if you want order by location or location_dest_id
  stock_barcodes/models/stock_barcodes_option.py
  stock_barcodes/views/stock_barcodes_option_view.xml
  stock_barcodes/wizard/stock_barcodes_read_picking.py
Labels: approved, bot is merging ⏳

#602 [15.0][IMP] stock_barcodes_gs1_secondary_unit: Make secondary_uom_qty required if product is set
  stock_barcodes_gs1_secondary_unit/wizard/stock_barcodes_read_picking_views.xml
Labels: approved, bot is merging ⏳
